/* ===================================================================
   Reading Boost — Curriculum Data
   A structured-literacy (Orton-Gillingham style) scope & sequence.
   Each level introduces a small set of sound patterns, then practices
   them through decodable words, heart (irregular) words, sentences,
   and a short story. Levels build on each other in order.

   words: [word, emoji, graphemes]  — graphemes are the sound chunks
          used for the "sound boxes" (e.g. "sh|i|p", "c|a_e|k").
   =================================================================== */

const READING_LEVELS = [
  {
    id: 1,
    title: 'Short A',
    icon: '🍎',
    grades: 'K–1',
    focus: 'Letters a, m, s, t, p, n, c and the short "a" sound',
    sounds: [
      { g: 'a', key: 'apple',  emoji: '🍎' },
      { g: 'm', key: 'moon',   emoji: '🌙' },
      { g: 's', key: 'sun',    emoji: '☀️' },
      { g: 't', key: 'tiger',  emoji: '🐯' },
      { g: 'p', key: 'pig',    emoji: '🐷' },
      { g: 'n', key: 'nest',   emoji: '🪺' },
      { g: 'c', key: 'cat',    emoji: '🐱' },
    ],
    words: [
      ['cat', '🐱', 'c|a|t'], ['map', '🗺️', 'm|a|p'], ['pan', '🍳', 'p|a|n'],
      ['man', '👨', 'm|a|n'], ['nap', '😴', 'n|a|p'], ['mat', '🟫', 'm|a|t'],
      ['cap', '🧢', 'c|a|p'], ['can', '🥫', 'c|a|n'],
    ],
    heartWords: ['the', 'a', 'I', 'is'],
    sentences: ['Sam sat.', 'The cat sat.', 'A man can nap.', 'Pam can tap the pan.'],
    story: {
      title: 'Sam the Cat',
      text: 'Sam is a cat. Sam sat on a mat. Sam can nap. The man can pat Sam.',
      question: 'Who is Sam?',
      choices: ['A cat', 'A man', 'A map'],
      answer: 0,
    },
    storyOlder: {
      title: 'Camp',
      text: 'Sam is at camp. Sam can scan the map. Tam can stamp the map. A cat naps at the camp. Sam can pat the cat.',
      question: 'What can Sam scan?',
      choices: ['The map', 'The cat', 'A pan'],
      answer: 0,
    },
  },
  {
    id: 2,
    title: 'Short I',
    icon: '🐷',
    grades: 'K–1',
    focus: 'Short "i" plus f, d, h, g',
    sounds: [
      { g: 'i', key: 'igloo',  emoji: '🛖' },
      { g: 'f', key: 'fish',   emoji: '🐟' },
      { g: 'd', key: 'dog',    emoji: '🐶' },
      { g: 'h', key: 'hat',    emoji: '🎩' },
      { g: 'g', key: 'goat',   emoji: '🐐' },
    ],
    words: [
      ['pig', '🐷', 'p|i|g'], ['dig', '⛏️', 'd|i|g'], ['fin', '🦈', 'f|i|n'],
      ['hat', '🎩', 'h|a|t'], ['pin', '📌', 'p|i|n'], ['sit', '🪑', 's|i|t'],
      ['fan', '🪭', 'f|a|n'], ['hid', '🙈', 'h|i|d'],
    ],
    heartWords: ['has', 'to', 'was', 'his'],
    sentences: ['The pig is big.', 'Tim hid the hat.', 'A fish has a fin.', 'Dad can dig a pit.'],
    story: {
      title: 'The Big Pig',
      text: 'Tim has a big pig. The pig can dig a pit. The pig sat in the pit. Tim was mad!',
      question: 'What did the pig dig?',
      choices: ['A hat', 'A pit', 'A map'],
      answer: 1,
    },
    storyOlder: {
      title: 'The Dig',
      text: 'Tim and Matt dig in the sand. Tim hits a big tin. In the tin is a map. The map has a big X. Tim and Matt dig at the X!',
      question: 'What was in the tin?',
      choices: ['A hat', 'A map', 'Sand'],
      answer: 1,
    },
  },
  {
    id: 3,
    title: 'Short O',
    icon: '🐶',
    grades: 'K–1',
    focus: 'Short "o" plus b, l, r',
    sounds: [
      { g: 'o', key: 'octopus', emoji: '🐙' },
      { g: 'b', key: 'ball',    emoji: '⚽' },
      { g: 'l', key: 'lion',    emoji: '🦁' },
      { g: 'r', key: 'rabbit',  emoji: '🐰' },
    ],
    words: [
      ['dog', '🐶', 'd|o|g'], ['log', '🪵', 'l|o|g'], ['pot', '🍲', 'p|o|t'],
      ['mop', '🧹', 'm|o|p'], ['top', '🔝', 't|o|p'], ['rob', '🦹', 'r|o|b'],
      ['hot', '🔥', 'h|o|t'], ['bat', '🦇', 'b|a|t'],
    ],
    heartWords: ['you', 'said', 'what', 'of'],
    sentences: ['The dog is on a log.', 'Bob has a hot pot.', 'Rob got a mop.', 'The cat is not on top.'],
    story: {
      title: 'Bob and the Hot Pot',
      text: 'Bob has a dog. The dog sat on a log. Bob got a hot pot. The dog did not sit on the pot!',
      question: 'Where did the dog sit?',
      choices: ['On the pot', 'On a log', 'On a bed'],
      answer: 1,
    },
    storyOlder: {
      title: 'The Lab Robot',
      text: 'Rob has a lab. In the lab is a robot. The robot can lift a log. It can mop. Rob said, "Stop, robot!" The robot did not stop. It hit a lot of pots!',
      question: 'What did the robot hit?',
      choices: ['A log', 'A lot of pots', 'Rob'],
      answer: 1,
    },
  },
  {
    id: 4,
    title: 'Short U & E',
    icon: '🐛',
    grades: 'K–1',
    focus: 'Short "u" and short "e" plus j, w, k',
    sounds: [
      { g: 'u', key: 'umbrella', emoji: '☂️' },
      { g: 'e', key: 'egg',      emoji: '🥚' },
      { g: 'j', key: 'jam',      emoji: '🍓' },
      { g: 'w', key: 'web',      emoji: '🕸️' },
      { g: 'k', key: 'kite',     emoji: '🪁' },
    ],
    words: [
      ['bug', '🐛', 'b|u|g'], ['sun', '☀️', 's|u|n'], ['cup', '☕', 'c|u|p'],
      ['bed', '🛏️', 'b|e|d'], ['net', '🥅', 'n|e|t'], ['web', '🕸️', 'w|e|b'],
      ['jet', '✈️', 'j|e|t'], ['red', '🔴', 'r|e|d'],
    ],
    heartWords: ['are', 'they', 'do', 'he'],
    sentences: ['The bug is in the web.', 'Ted has a red cup.', 'The sun is hot.', 'Jen can get the net.'],
    story: {
      title: 'Ted and the Bug',
      text: 'Ted has a red net. A bug is on a web. Ted can get the bug in his net. The bug is his pet!',
      question: 'What color is the net?',
      choices: ['Red', 'Tan', 'Pink'],
      answer: 0,
    },
    storyOlder: {
      title: 'The Big Kick',
      text: 'Jen and Kim are on a team. Jen can run. Kim can kick. Kim kicks it to Jen. Jen runs and kicks. It hits the net! Jen and Kim win!',
      question: 'Who kicked it into the net?',
      choices: ['Kim', 'Jen', 'The fans'],
      answer: 1,
    },
  },
  {
    id: 5,
    title: 'Digraphs',
    icon: '🐟',
    grades: '1',
    focus: 'Two letters, one sound: sh, ch, th, ck',
    sounds: [
      { g: 'sh', key: 'ship',  emoji: '🚢' },
      { g: 'ch', key: 'chick', emoji: '🐥' },
      { g: 'th', key: 'thumb', emoji: '👍' },
      { g: 'ck', key: 'duck',  emoji: '🦆' },
    ],
    words: [
      ['ship', '🚢', 'sh|i|p'], ['fish', '🐟', 'f|i|sh'], ['chin', '🧔', 'ch|i|n'],
      ['duck', '🦆', 'd|u|ck'], ['bath', '🛁', 'b|a|th'], ['shell', '🐚', 'sh|e|ll'],
      ['chick', '🐥', 'ch|i|ck'], ['sock', '🧦', 's|o|ck'],
    ],
    heartWords: ['there', 'where', 'come', 'went'],
    sentences: ['The duck is in the bath.', 'A fish is in the shell.', 'Chad has a red sock.', 'The ship is on the dock.'],
    story: {
      title: 'The Fish Shop',
      text: 'Chad and Beth went to a fish shop. Chad got a thin fish. Beth got a chip. Then they sat on the deck.',
      question: 'What did Beth get?',
      choices: ['A fish', 'A chip', 'A shell'],
      answer: 1,
    },
    storyOlder: {
      title: 'The Fish on the Ship',
      text: 'Chad and his dad went to fish on a ship. Chad cast his rod. Then, a big tug! Chad did not quit. At last, Chad got a fish as big as a dish. Chad and his dad got a pic of it.',
      question: 'Where did Chad and his dad fish?',
      choices: ['On a dock', 'On a ship', 'In a pond'],
      answer: 1,
    },
  },
  {
    id: 6,
    title: 'Blends',
    icon: '🐸',
    grades: '1',
    focus: 'Two consonants, two sounds: st, fl, tr, cr, fr, nd, mp',
    sounds: [
      { g: 'st', key: 'star',  emoji: '⭐' },
      { g: 'fl', key: 'flag',  emoji: '🚩' },
      { g: 'tr', key: 'tree',  emoji: '🌳' },
      { g: 'cr', key: 'crab',  emoji: '🦀' },
      { g: 'fr', key: 'frog',  emoji: '🐸' },
      { g: 'nd', key: 'hand',  emoji: '✋' },
      { g: 'mp', key: 'lamp',  emoji: '💡' },
    ],
    words: [
      ['frog', '🐸', 'f|r|o|g'], ['crab', '🦀', 'c|r|a|b'], ['flag', '🚩', 'f|l|a|g'],
      ['hand', '✋', 'h|a|n|d'], ['lamp', '💡', 'l|a|m|p'], ['drum', '🥁', 'd|r|u|m'],
      ['tent', '⛺', 't|e|n|t'], ['plant', '🪴', 'p|l|a|n|t'],
    ],
    heartWords: ['some', 'one', 'from', 'want'],
    sentences: ['The frog can jump.', 'The crab has a flag.', 'Stan sat in the tent.', 'Fran has a drum.'],
    story: {
      title: 'Frog on a Trip',
      text: 'A frog went on a trip. The frog had to jump from a plant to a log. The frog met a crab. The crab had a flag. The frog and the crab had a grand trip!',
      question: 'Who had a flag?',
      choices: ['The frog', 'The crab', 'The plant'],
      answer: 1,
    },
    storyOlder: {
      title: 'The Sprint',
      text: 'Brad and Fran went to the track to sprint. Fran felt strong. Brad felt stiff. Bang! They ran. At the end, Fran was just a step in front. Then they had a big drink and a rest.',
      question: 'Who was in front at the end?',
      choices: ['Brad', 'Fran', 'The coach'],
      answer: 1,
    },
  },
  {
    id: 7,
    title: 'Magic E',
    icon: '🪁',
    grades: '1–2',
    focus: 'Silent "e" makes the vowel say its name: a_e, i_e, o_e, u_e',
    sounds: [
      { g: 'a_e', key: 'cake', emoji: '🎂' },
      { g: 'i_e', key: 'kite', emoji: '🪁' },
      { g: 'o_e', key: 'rose', emoji: '🌹' },
      { g: 'u_e', key: 'cube', emoji: '🧊' },
    ],
    words: [
      ['cake', '🎂', 'c|a_e|k'], ['kite', '🪁', 'k|i_e|t'], ['bike', '🚲', 'b|i_e|k'],
      ['rose', '🌹', 'r|o_e|s'], ['bone', '🦴', 'b|o_e|n'], ['cube', '🧊', 'c|u_e|b'],
      ['lake', '🏞️', 'l|a_e|k'], ['home', '🏠', 'h|o_e|m'],
    ],
    heartWords: ['water', 'would', 'could', 'were'],
    sentences: ['Mike has a kite.', 'Jane ate the cake.', 'The dog has a bone.', 'We rode bikes home.'],
    story: {
      title: 'Kite at the Lake',
      text: 'Jane and Mike rode bikes to the lake. Mike had a kite. The wind made the kite rise up, up, up! Jane ate cake on the dock. It was a fine time.',
      question: 'What did Mike have?',
      choices: ['A cake', 'A bike bell', 'A kite'],
      answer: 2,
    },
    storyOlder: {
      title: 'The Bike Race',
      text: 'Jake and Kate rode bikes in a race. The route went up a hill and past a lake. Jake had a flat tire and had to stop. Kate came back to help. They made it home in time. It was not a win, but it was a fine ride.',
      question: 'Why did Jake stop?',
      choices: ['He had a flat tire', 'He saw a lake', 'He won the race'],
      answer: 0,
    },
  },
  {
    id: 8,
    title: 'Vowel Teams',
    icon: '⛵',
    grades: '1–2',
    focus: 'Two vowels work together: ai, ay, ee, ea, oa',
    sounds: [
      { g: 'ai', key: 'rain',  emoji: '🌧️' },
      { g: 'ay', key: 'hay',   emoji: '🌾' },
      { g: 'ee', key: 'tree',  emoji: '🌳' },
      { g: 'ea', key: 'leaf',  emoji: '🍃' },
      { g: 'oa', key: 'boat',  emoji: '⛵' },
    ],
    words: [
      ['rain', '🌧️', 'r|ai|n'], ['tree', '🌳', 't|r|ee'], ['boat', '⛵', 'b|oa|t'],
      ['seal', '🦭', 's|ea|l'], ['goat', '🐐', 'g|oa|t'], ['bee', '🐝', 'b|ee'],
      ['snail', '🐌', 's|n|ai|l'], ['tray', '🍱', 't|r|ay'],
    ],
    heartWords: ['people', 'been', 'their', 'many'],
    sentences: ['The bee is in the tree.', 'A goat is on the boat.', 'The snail is in the rain.', 'We play at the beach.'],
    story: {
      title: 'A Day at the Beach',
      text: 'It was a hot day. Dee and Ray went to the beach. They played in the sea. Ray had a toy boat. A seal swam up to the boat! They had a great day.',
      question: 'What swam up to the boat?',
      choices: ['A goat', 'A seal', 'A bee'],
      answer: 1,
    },
    storyOlder: {
      title: 'Race Day',
      text: 'On race day, Dean waited at the lane. He had trained each week. Gail said, "Stay calm and keep your feet steady." Dean sped down the lane and beat his best time. His team cheered.',
      question: 'What did Dean beat?',
      choices: ['Gail', 'His best time', 'The whole team'],
      answer: 1,
    },
  },
  {
    id: 9,
    title: 'Bossy R',
    icon: '🌟',
    grades: '2',
    focus: 'R changes the vowel: ar, or, er, ir, ur',
    sounds: [
      { g: 'ar', key: 'car',   emoji: '🚗' },
      { g: 'or', key: 'corn',  emoji: '🌽' },
      { g: 'er', key: 'fern',  emoji: '🌿' },
      { g: 'ir', key: 'bird',  emoji: '🐦' },
      { g: 'ur', key: 'turtle', emoji: '🐢' },
    ],
    words: [
      ['car', '🚗', 'c|ar'], ['star', '⭐', 's|t|ar'], ['corn', '🌽', 'c|or|n'],
      ['fork', '🍴', 'f|or|k'], ['bird', '🐦', 'b|ir|d'], ['shirt', '👕', 'sh|ir|t'],
      ['farm', '🚜', 'f|ar|m'], ['church', '⛪', 'ch|ur|ch'],
    ],
    heartWords: ['laugh', 'eye', 'busy', 'only'],
    sentences: ['The bird is on the barn.', 'Carl ate the corn.', 'The car is dark.', 'Her shirt has a star.'],
    story: {
      title: 'The Farm',
      text: 'Carl has a farm. On the farm there is a barn and lots of corn. A bird sat on the barn. A girl named Fern fed the hens. At dark, the stars came out.',
      question: 'What sat on the barn?',
      choices: ['A bird', 'A hen', 'A star'],
      answer: 0,
    },
    storyOlder: {
      title: 'The Storm',
      text: 'The storm came after dark. The wind was so strong it tore a branch off the birch tree. Marta and her brother had no power, so they lit a lantern. They sat in a warm corner and played cards until the storm was over.',
      question: 'What did they use for light?',
      choices: ['A lantern', 'A flashlight', 'The stars'],
      answer: 0,
    },
  },
  {
    id: 10,
    title: 'Big Words',
    icon: '🌈',
    grades: '2–3',
    chunks: true,
    focus: 'Two-syllable and compound words — chunk it, then read it',
    sounds: [
      { g: 'sun·set',  key: 'sunset',  emoji: '🌅' },
      { g: 'rab·bit',  key: 'rabbit',  emoji: '🐇' },
      { g: 'cup·cake', key: 'cupcake', emoji: '🧁' },
      { g: 'rain·bow', key: 'rainbow', emoji: '🌈' },
    ],
    words: [
      ['sunset', '🌅', 'sun|set'], ['rabbit', '🐇', 'rab|bit'], ['cupcake', '🧁', 'cup|cake'],
      ['rainbow', '🌈', 'rain|bow'], ['basket', '🧺', 'bas|ket'], ['picnic', '🧺', 'pic|nic'],
      ['napkin', '🧻', 'nap|kin'], ['football', '🏈', 'foot|ball'],
    ],
    heartWords: ['because', 'friend', 'again', 'sister'],
    sentences: ['The rabbit ate a cupcake.', 'We had a picnic at sunset.', 'Kim got a basket.', 'Look at the rainbow!'],
    story: {
      title: 'The Picnic',
      text: 'Max and his sister had a picnic in the garden. They packed a basket with cupcakes and napkins. A rabbit hopped up to the blanket. After the picnic, they saw a rainbow at sunset.',
      question: 'What hopped up to the blanket?',
      choices: ['A rabbit', 'A frog', 'A bird'],
      answer: 0,
    },
    storyOlder: {
      title: 'The Contest',
      text: 'Kendra entered the science contest with a robot she built from a basket and a magnet. The robot could pick up tin cans. At the contest, it stopped working! Kendra did not panic. She found the problem with the magnet, fixed it, and the robot picked up ten cans. She got second place.',
      question: 'What did Kendra do when the robot stopped?',
      choices: ['She gave up', 'She fixed the magnet', 'She went home'],
      answer: 1,
    },
  },
  {
    id: 11,
    title: 'Word Endings',
    icon: '🦘',
    grades: '2–3',
    chunks: true,
    focus: 'Suffixes change a word: -ing, -ed, -est, -ful, -less, -ly',
    sounds: [
      { g: '-ing',  key: 'jumping',  emoji: '🦘', meaning: 'doing it now' },
      { g: '-ed',   key: 'painted',  emoji: '🎨', meaning: 'it already happened' },
      { g: '-est',  key: 'fastest',  emoji: '🏃', meaning: 'the most' },
      { g: '-ful',  key: 'helpful',  emoji: '🤝', meaning: 'full of' },
      { g: '-less', key: 'careless', emoji: '🫗', meaning: 'without' },
      { g: '-ly',   key: 'slowly',   emoji: '🐢', meaning: 'in a way that is' },
    ],
    words: [
      ['jumping', '🦘', 'jump|ing'], ['painted', '🎨', 'paint|ed'], ['fastest', '🏃', 'fast|est'],
      ['helpful', '🤝', 'help|ful'], ['thankful', '🙏', 'thank|ful'], ['slowly', '🐢', 'slow|ly'],
      ['quickly', '⚡', 'quick|ly'], ['spotless', '✨', 'spot|less'],
    ],
    heartWords: ['though', 'enough', 'thought', 'caught'],
    sentences: ['The kangaroo is jumping.', 'She was thankful for the gift.', 'The turtle walked slowly.', 'He painted the fence.'],
    story: {
      title: 'The Helpful Neighbor',
      text: 'Hank Hardy was careless and left his garden hose running all night. His yard flooded quickly. Ana, his helpful neighbor, rushed over. She turned off the water and helped him sweep the mud. Hank was thankful. The next day, he painted a sign that said, "Thank you, Ana!"',
      question: 'What did Hank leave running?',
      choices: ['His car', 'His garden hose', 'His radio'],
      answer: 1,
    },
  },
  {
    id: 12,
    title: 'Prefixes',
    icon: '🔓',
    grades: '3–4',
    chunks: true,
    focus: 'Prefixes change the meaning: un-, re-, pre-, dis-, mis-',
    sounds: [
      { g: 'un-',  key: 'unlock',   emoji: '🔓', meaning: 'not, or the opposite' },
      { g: 're-',  key: 'redo',     emoji: '🔁', meaning: 'again' },
      { g: 'pre-', key: 'preview',  emoji: '👀', meaning: 'before' },
      { g: 'dis-', key: 'dislike',  emoji: '👎', meaning: 'not, or the opposite' },
      { g: 'mis-', key: 'misspell', emoji: '❌', meaning: 'wrongly' },
    ],
    words: [
      ['unlock', '🔓', 'un|lock'], ['redo', '🔁', 're|do'], ['preview', '👀', 'pre|view'],
      ['dislike', '👎', 'dis|like'], ['misspell', '❌', 'mis|spell'], ['unhappy', '😞', 'un|hap|py'],
      ['rewrite', '✍️', 're|write'], ['disappear', '🫥', 'dis|ap|pear'],
    ],
    heartWords: ['answer', 'different', 'special', 'beautiful'],
    sentences: ['Please unlock the door.', 'I will redo my homework.', 'Do not misspell your name.', 'The magician made the coin disappear.'],
    story: {
      title: 'Rewriting the Ending',
      text: 'Leo disliked the ending of his story. It felt unfinished and a little unfair to the hero. His teacher said he could rewrite it. Leo reread the whole thing, fixed a few misspelled words, and gave the hero a better ending. When he shared it, the class was not disappointed.',
      question: 'Why did Leo rewrite his story?',
      choices: ['He lost it', 'He disliked the ending', 'His friend asked him to'],
      answer: 1,
    },
  },
  {
    id: 13,
    title: 'Big Chunks',
    icon: '🧭',
    grades: '4–5',
    chunks: true,
    focus: 'Long-word chunks: -tion, -sion, -ture, -ous',
    sounds: [
      { g: '-tion', key: 'station',   emoji: '🚉', meaning: 'says "shun"' },
      { g: '-sion', key: 'television', emoji: '📺', meaning: 'says "zhun" or "shun"' },
      { g: '-ture', key: 'picture',   emoji: '🖼️', meaning: 'says "cher"' },
      { g: '-ous',  key: 'famous',    emoji: '🌟', meaning: 'says "us" — full of' },
    ],
    words: [
      ['picture', '🖼️', 'pic|ture'], ['nature', '🌿', 'na|ture'], ['station', '🚉', 'sta|tion'],
      ['vacation', '🏖️', 'va|ca|tion'], ['famous', '🌟', 'fa|mous'], ['television', '📺', 'tel|e|vi|sion'],
      ['adventure', '🧭', 'ad|ven|ture'], ['invention', '💡', 'in|ven|tion'],
    ],
    heartWords: ['ocean', 'island', 'straight', 'piece'],
    sentences: ['We took a picture of nature.', 'The train left the station.', 'Her invention made her famous.', 'We went on an adventure.'],
    story: {
      title: 'The Invention',
      text: 'On vacation, Maria had an idea for an invention: a picture frame that waters plants. She drew a design and tested it at the nature station near the lake. The first version leaked everywhere! After some adjustments, it worked. Her invention was on the local television news, and for one day, she was famous.',
      question: 'What did Maria\'s invention do?',
      choices: ['It took pictures', 'It watered plants', 'It cleaned the lake'],
      answer: 1,
    },
  },
  {
    id: 14,
    title: 'Word Roots',
    icon: '🔬',
    grades: '5–8',
    chunks: true,
    focus: 'Greek & Latin roots unlock thousands of words: tele, graph, port, struct, dict, scope',
    sounds: [
      { g: 'tele',   key: 'telephone',  emoji: '☎️', meaning: 'far' },
      { g: 'graph',  key: 'autograph',  emoji: '✍️', meaning: 'write or draw' },
      { g: 'port',   key: 'transport',  emoji: '🚚', meaning: 'carry' },
      { g: 'struct', key: 'construct',  emoji: '🏗️', meaning: 'build' },
      { g: 'dict',   key: 'predict',    emoji: '🔮', meaning: 'say' },
      { g: 'scope',  key: 'microscope', emoji: '🔬', meaning: 'look at' },
    ],
    words: [
      ['telephone', '☎️', 'tele|phone'], ['autograph', '✍️', 'auto|graph'], ['transport', '🚚', 'trans|port'],
      ['construct', '🏗️', 'con|struct'], ['predict', '🔮', 'pre|dict'], ['microscope', '🔬', 'micro|scope'],
      ['photograph', '📷', 'photo|graph'], ['telescope', '🔭', 'tele|scope'],
    ],
    heartWords: ['science', 'language', 'separate', 'necessary'],
    sentences: ['I called my friend on the telephone.', 'The truck will transport the logs.', 'Can you predict the weather?', 'Look through the microscope.'],
    story: {
      title: 'Volcano Watch',
      text: 'Scientists use many tools to predict when a volcano might erupt. A seismograph records how much the ground shakes. A satellite can photograph the volcano from space. If the signs point to danger, crews transport people to safety. These predictions can save thousands of lives.',
      question: 'What does a seismograph record?',
      choices: ['How hot the lava is', 'How much the ground shakes', 'How tall the volcano is'],
      answer: 1,
    },
  },
];

/* ===================================================================
   Grade settings — each grade gets its own starting point, lesson size,
   tone, vocabulary practice and reading-rate goal.
   wcpm = typical spring oral reading rate (50th percentile, words per
   minute; Hasbrouck & Tindal norms). Shown to grown-ups as a long-term
   goal only — for kids with learning differences, growth matters most.
   =================================================================== */
const GRADES = {
  K: { label: 'Kindergarten', band: 'young', start: 1,  wcpm: null, vocab: 0, blend: 5, spell: 3 },
  1: { label: 'Grade 1',      band: 'young', start: 1,  wcpm: 60,   vocab: 0, blend: 6, spell: 4 },
  2: { label: 'Grade 2',      band: 'young', start: 4,  wcpm: 100,  vocab: 2, blend: 6, spell: 4 },
  3: { label: 'Grade 3',      band: 'mid',   start: 7,  wcpm: 112,  vocab: 3, blend: 7, spell: 5 },
  4: { label: 'Grade 4',      band: 'mid',   start: 9,  wcpm: 133,  vocab: 3, blend: 7, spell: 5 },
  5: { label: 'Grade 5',      band: 'mid',   start: 11, wcpm: 146,  vocab: 3, blend: 8, spell: 5 },
  6: { label: 'Grade 6',      band: 'teen',  start: 12, wcpm: 146,  vocab: 4, blend: 8, spell: 5 },
  7: { label: 'Grade 7',      band: 'teen',  start: 13, wcpm: 150,  vocab: 4, blend: 8, spell: 5 },
  8: { label: 'Grade 8',      band: 'teen',  start: 14, wcpm: 151,  vocab: 4, blend: 8, spell: 5 },
};
const GRADE_KEYS = ['K', '1', '2', '3', '4', '5', '6', '7', '8'];

/* Short movement breaks — help kids with ADHD (and everyone!) reset focus */
const BRAIN_BREAKS = [
  { emoji: '🐸', text: 'Do 5 frog jumps!' },
  { emoji: '🐱', text: 'Stretch up tall like a cat, then touch your toes.' },
  { emoji: '🌬️', text: 'Smell the flower, blow out the candle. Breathe in… and out. 3 times.' },
  { emoji: '🐝', text: 'Buzz like a bee and flap your arms 10 times!' },
  { emoji: '🧘', text: 'Squeeze your hands into fists… now let go. Do it 5 times.' },
  { emoji: '🦩', text: 'Stand on one foot like a flamingo. Count to 10!' },
  { emoji: '🙆', text: 'Give yourself a big hug and say "I can do hard things!"' },
];

/* Older readers (grades 3–8) get grown-up breaks and a less babyish tone */
const BRAIN_BREAKS_OLDER = [
  { emoji: '🧍', text: 'Stand up and stretch tall for 20 seconds.' },
  { emoji: '🟦', text: 'Box breathing: in for 4, hold for 4, out for 4, hold for 4. Do it twice.' },
  { emoji: '💪', text: 'Do 10 wall push-ups or 10 squats.' },
  { emoji: '🔄', text: 'Roll your shoulders back 10 times, then forward 10 times.' },
  { emoji: '👀', text: 'Rest your eyes: look at something far away for 20 seconds.' },
  { emoji: '✊', text: 'Squeeze every muscle for 5 seconds, then relax. Repeat 3 times.' },
];

/* Encouragement that praises effort, not just correctness (growth mindset) */
const PRAISE = [
  'You worked hard on that!', 'Great focus!', 'You kept trying — that is how brains grow!',
  'Super reading!', 'Nice sounding out!', 'You are getting stronger every day!',
];
const GENTLE_RETRY = [
  'Almost! Let\'s try again together.', 'Good try! Listen and try once more.',
  'Mistakes help us learn. Try again!', 'Take a breath — you\'ve got this.',
];
const PRAISE_OLDER = [
  'Nice work.', 'Solid reading.', 'That effort is paying off.',
  'You stuck with it — that is how skills grow.', 'Strong decoding!', 'Good focus.',
];
const GENTLE_RETRY_OLDER = [
  'Close — give it another look.', 'Not quite. Slow down and chunk it.',
  'Mistakes are just data. Try again.', 'Almost. Listen once more and retry.',
];
